language: android

addons:
    apt:
        packages:
        - libgd2-xpm
        - ia32-libs
        - ia32-libs-multiarch
        - git
        - libtool
        - automake

android:
    components:
    - platform-tools
    - android-21
    - build-tools-21.1.2
    - extra

jdk: oraclejdk7

notifications:
  email: false

before_install:
    - bash setup.sh
    - source env.sh

install:
    - bash install-package.sh

cache:
    directories:
    - $(pwd)/android-ndk-r10e

script:
    - bash build.sh
